#!/usr/bin/env python3
"""
Comprehensive test runner for AI Operating System Framework
Generated by TestGenie Agent
"""

import unittest
import sys
import os

def discover_and_run_tests():
    """Discover and run all tests in the tests directory"""
    # Add project root to path
    project_root = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, project_root)
    
    # Discover tests
    loader = unittest.TestLoader()
    start_dir = 'tests'
    
    if os.path.exists(start_dir):
        suite = loader.discover(start_dir, pattern='*_test.py')
    else:
        print("No tests directory found, creating one...")
        os.makedirs(start_dir, exist_ok=True)
        suite = unittest.TestSuite()
    
    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Print summary
    print(f"\n{'='*50}")
    print(f"Tests run: {result.testsRun}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")
    print(f"Success rate: {((result.testsRun - len(result.failures) - len(result.errors)) / max(result.testsRun, 1)) * 100:.1f}%")
    print(f"{'='*50}")
    
    return result.wasSuccessful()

if __name__ == '__main__':
    success = discover_and_run_tests()
    sys.exit(0 if success else 1)
