apiVersion: apps/v1
kind: Deployment
metadata:
  name: aimos-core
  namespace: aimos
  labels:
    app: aimos-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aimos-core
  template:
    metadata:
      labels:
        app: aimos-core
    spec:
      containers:
      - name: aimos-core
        image: aimos/core:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aimos-core-service
  namespace: aimos
spec:
  selector:
    app: aimos-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
